[package]
name = "huffman-coding-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"

[[bin]]
name = "encode"
path = "src/encoder.rs"

[[bin]]
name = "decode"
path = "src/decoder.rs"

